apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: kafka-ui-ingress
  namespace: kafka
spec:
  entryPoints:
    - kafka
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - kind: Service
          name: kafka-ui
          namespace: kafka
          port: 8080
