apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: airflow-ingress
  namespace: airflow
spec:
  entryPoints:
    - airflow
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - kind: Service
          name: airflow-webserver
          namespace: airflow
          port: 7070
