apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: datadiver-dev
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - "https://charts.jetstack.io"
    - "https://github.com/datadiverdev/datadiver-cert-manager.git"
    - "https://downloads.apache.org/flink/flink-kubernetes-operator-1.4.0"
    - "https://github.com/datadiverdev/datadiver-flink.git"
    - "https://charts.redpanda.com"
    - "https://github.com/datadiverdev/datadiver-redpanda.git"
    - "https://traefik.github.io/charts"
    - "https://github.com/datadiverdev/datadiver-traefik.git"
  destinations:
    - namespace: "*"
      server: "https://kubernetes.default.svc"