apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow-dev
  namespace: argocd
spec:
  project: datadiver-dev
  destination:
    server: "https://kubernetes.default.svc"
    namespace: airflow
  sources:
    - repoURL: "https://airflow.apache.org/"
      chart: airflow
      targetRevision: 1.8.0
      helm:
        valueFiles:
          - $values/helm/dev/values.yaml
    - repoURL: "https://github.com/datadiverdev/datadiver-airflow.git"
      targetRevision: dev
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true