apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: minio-console-ingress
  namespace: minio-operator
spec:
  entryPoints:
    - minio
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - kind: Service
          name: console
          namespace: minio-operator
          port: 9090
