apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
spec:
  kafka:
    version: 3.3.1
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: nodeport
        tls: false
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.3"
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          class: directpv-min-io
          size: 40Gi
          deleteClaim: false
          overrides:
            - broker: 0
              persistentVolumeClaim: data-kafka-cluster-0
            - broker: 1
              persistentVolumeClaim: data-kafka-cluster-1
            - broker: 2
              persistentVolumeClaim: data-kafka-cluster-2
    resources:
      requests:
        memory: 1Gi
        cpu: "250m"
      limits:
        memory: 2Gi
        cpu: "500m"
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      class: directpv-min-io
      size: 10Gi
      deleteClaim: false
    overrides:
      - broker: 0
        persistentVolumeClaim: data-kafka-zookeeper-0
      - broker: 1
        persistentVolumeClaim: data-kafka-zookeeper-1
      - broker: 2
        persistentVolumeClaim: data-kafka-zookeeper-2
    resources:
      requests:
        memory: 512Mi
        cpu: "250m"
      limits:
        memory: 1Gi
        cpu: "500m"
  entityOperator:
    tlsSidecar:
      resources:
        requests:
          cpu: 200m
          memory: 64Mi
        limits:
          cpu: 500m
          memory: 128Mi
    topicOperator:
      watchedNamespace: kafka
      reconciliationIntervalSeconds: 60
      logging:
        type: inline
        loggers:
          rootLogger.level: "INFO"
      resources:
        requests:
          memory: 512Mi
          cpu: "1"
        limits:
          memory: 512Mi
          cpu: "1"
    userOperator:
      watchedNamespace: kafka
      reconciliationIntervalSeconds: 60
      logging:
        type: inline
        loggers:
          rootLogger.level: INFO
      resources:
        requests:
          memory: 512Mi
          cpu: "1"
        limits:
          memory: 512Mi
          cpu: "1"